# Generated by Django 4.1.1 on 2022-11-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='verify_guide',
            field=models.CharField(choices=[('verified', 'verified'), ('denied', 'denied'), ('not_verified', 'not_verified')], default='not_verified', max_length=15),
        ),
    ]
