# Generated by Django 4.1.3 on 2022-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
        migrations.AddField(
            model_name='guide',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_image',
            field=models.ImageField(blank=True, upload_to='main/storeimg/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_image',
            field=models.ImageField(blank=True, upload_to='main/storeimg/'),
        ),
    ]
