# Generated by Django 4.1.3 on 2022-11-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPage',
        ),
    ]
