# Generated by Django 4.1.1 on 2022-11-05 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("content", models.TextField()),
                ("date", models.DateTimeField()),
                ("report", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_name", models.CharField(max_length=200)),
                ("province", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(default=0)),
                ("period", models.CharField(max_length=50)),
                ("amount", models.PositiveIntegerField(default=1)),
                ("information", models.TextField()),
                ("img", models.ImageField(blank=True, null=True, upload_to="")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "guide",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("review", models.ManyToManyField(blank=True, to="tour.review")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="review",
            name="reviewto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewto",
                to="tour.tour",
            ),
        ),
    ]
