# Generated by Django 4.1.1 on 2022-11-26 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='review',
            field=models.ManyToManyField(blank=True, to='tour.review'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_tour',
            field=models.ManyToManyField(blank=True, related_name='this_tour', to='tour.tour'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booktour',
            name='member',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booktour',
            name='tour',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_tour', to='tour.tour'),
        ),
    ]
