# Generated by Django 4.1.3 on 2022-11-13 09:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/tour/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
