# Generated by Django 4.1.1 on 2022-11-15 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='status',
            new_name='verify_tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BookTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_member', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_member', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_tour', to='tour.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='book_tour', to='tour.booktour'),
        ),
    ]
