# Generated by Django 4.1.1 on 2022-11-11 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_remove_review_author_remove_review_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 11, 12, 44, 19, 228786), null=True),
        ),
    ]
