# Generated by Django 4.1.1 on 2022-11-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_rename_status_tour_verify_tour_tour_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktour',
            name='verify_member',
            field=models.CharField(choices=[('verify', 'verify'), ('problem', 'problem'), ('not_verify', 'not_verify')], default='not_verify', max_length=15),
        ),
    ]
