# Generated by Django 4.1.1 on 2022-11-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_alter_booktour_verify_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktour',
            name='verify_member',
            field=models.CharField(choices=[('verified', 'verified'), ('denied', 'denied'), ('not_verified', 'not_verified')], default='not_verified', max_length=15),
        ),
    ]
