# Generated by Django 4.1.1 on 2022-11-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_booktour_verify_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='avg_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
