# Generated by Django 4.1.1 on 2022-11-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_booktour_verify_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='avg_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
