# Generated by Django 4.1.1 on 2022-11-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_tour_avg_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='avg_reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
