# Generated by Django 4.1.1 on 2022-11-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_alter_tour_avg_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='avg_reviews',
            new_name='avg_rating',
        ),
    ]
