# Generated by Django 4.1.1 on 2022-11-11 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 11, 17, 43, 26, 30380), null=True),
        ),
    ]
